service: runesapi
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 6

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - .gitignore
    - .git/**

functions:
  add:
    handler: src/handler.add
    events:
      - http:
          path: /add
          method: POST
          cors: true
  find:
    handler: src/handler.find
    events:
      - http:
          path: /find
          method: GET
          cors: true
  remove:
    handler: src/handler.remove
    events:
      - http:
          path: /remove
          method: DELETE
          cors: true
